version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017
      
  movie-service:
    build: movie-service
    ports:
      - 7100:7000

  movie-mongodb:
    build: mongodb
    ports:
      - 27000:27017
      
  rent-service:
    build: rent-service
    ports:
      - 7200:7000

  rent-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  monitoring:
    build: monitoring
